-- LIFEGRID STEP 45: in-app role onboarding
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.account_registrations (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  requested_role text not null check (
    requested_role in ('ambulance','hospital','resource_provider')
  ),
  full_name text,
  email text,
  phone text,
  organization_name text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (
    status in ('pending','approved','rejected')
  ),
  reviewed_by uuid,
  reviewed_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_account_registrations_status
on public.account_registrations(status, created_at desc);

alter table public.account_registrations enable row level security;

drop policy if exists "LIFEGRID own registration read" on public.account_registrations;
create policy "LIFEGRID own registration read"
on public.account_registrations for select to authenticated
using (
  auth.uid() = auth_user_id
  or coalesce(auth.jwt() -> 'app_metadata' ->> 'role','') in ('coordinator','admin')
);

commit;
